CREATE TABLE joins_homework.CUSTOMERS (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(25) NOT NULL,
    surname VARCHAR(35) NOT NULL,
    age INT,
    phone_number VARCHAR(15) NOT NULL
);

INSERT INTO joins_homework.CUSTOMERS (name, surname, age, phone_number)
VALUES
('Alexey', 'Ivanov', 30, '1234567890'),
('John', 'Smith', 25, '9876543210'),
('Maria', 'Lopez', 35, '5558887777'),
('Sophia', 'Brown', 28, '4445556666');