CREATE TABLE joins_homework.ORDERS(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    customer_id INT,
    product_name TEXT NOT NULL,
    amount INT NOT NULL,
    FOREIGN KEY (customer_id) REFERENCES joins_homework.CUSTOMERS(id)
);

INSERT INTO joins_homework.ORDERS (date, customer_id, product_name, amount)
VALUES
   ('2025-01-15', 1, 'Laptop', 1),
   ('2025-01-16', 2, 'Smartphone', 2),
   ('2025-01-17', 3, 'Tablet', 3),
   ('2025-01-18', 4, 'Monitor', 1);